### ISSUE TITLE
Stars implementation missing

### ISSUE THREAD

**Issue by samuveth** [damianof/large-scale-apps-my-vue3-project#2]
Page 43 it shows how the page should look, with the second item clicked. At that point in the book there hasn't been any star icons added to the app and there is no way to see in the UI if the second list item was clicked or not.

**Comment by damianof** [comment]
Thank you for reporting this. I plan to publish an update with several revisions including this, plus a few new chapters to complete the book within the next 30 days.

**Comment by damianof** [comment]
@samuveth It seems to be that pages 33-34 introduce the selected-indicator changes. Am I missing something else?
