### ISSUE TITLE
Running Sample "Up to Chapter 5" broken layout in Firefox 

### ISSUE THREAD

**Issue by scheinercc** [damianof/large-scale-apps-my-vue3-project#4]
https://largescaleapps.com/chapter5/#/
<img width="539" alt="image" src="https://user-images.githubusercontent.com/817856/114667507-e3316680-9d42-11eb-811b-6391a935ed3a.png">

Tested with Firefox 88 (current Dev Edition; released in ~5 days: https://wiki.mozilla.org/Release_Management/Calendar) on macOS Big Sur 13.2.x 

It seems this can be fixed by changing 

```
li.item {
  outline: ...
}
```

to 

```
li.item {
  border: ...
}
```

**Comment by scheinercc** [comment]
I also filed a ticket against Firefox in case there is something funny going on with the browser, but it doesn't seem like it. `border` seems to be the more solid choice: https://bugzilla.mozilla.org/show_bug.cgi?id=1705005#c1

**Comment by damianof** [comment]
Thank you for reporting this.
Since the main goal of the book was not to support all browsers, I'll keep the outline for now and let the readers know that using border fixes the issue in Firefox.
