### ISSUE TITLE
fix: replace `VUE_APP_CLIENT` by `VUE_APP_CONFIG` in the book

### ISSUE THREAD

**Issue by shoichiaizawa** [damianof/large-scale-apps-my-vue3-project#5]
Hi, I am working on your book!
Thank you for authoring this :D

Along the way, I found a minor error in Chapter 1, where `cross-env` is introduced.
The env var that `cross-env` sees is now `VUE_APP_CONFIG` in the companion code:

https://github.com/damianof/large-scale-apps-my-vue3-project/blob/8203a2f053c14e818566106ed8a4b61601b13219/composition-api/package.json#L6-L16

In Chapter 1 [1] of the book, however, the `VUE_APP_CLIENT` env var is used.

It would be fantastic if you could quickly fix up this for the other fellow learners 🖖 

---

\[1]: There may be more in the latter chapter/s.

Related commit: https://github.com/damianof/large-scale-apps-my-vue3-project/commit/3b9aaab40d586919aa279fea70b7e4a511fc5c64#diff-c0a267061f20e7ffb71f19e72e3fa3314d436ca7db80f55d9f02981ea56bb527

**Comment by damianof** [comment]
Sorry for the delay. Thank you for the nice words and for reporting this. I'll look into this in the next week or so, as just had my daughter undergoing a major surgery.

**Comment by damianof** [comment]
Ok so the repository is further ahead than Chapter 1, as this represent the book completion as of the last Chapter.
You'll see that Chapter 1 starts with VUE_APP_API_CLIENT, but later we'll refactor this and use a technique that allows us to only switch the config file we want to use with the env variable called VUE_APP_CONFIG. (you can see this done in the book start with "Chapter 14 - App Configuration". One of the commits is https://github.com/damianof/large-scale-apps-my-vue3-project/commit/18ca128ed047953e9b2c7502133c7f77c40af1ab)

I hope this answers your question.
