### ISSUE TITLE
Can't run tests on node

### ISSUE THREAD

**Issue by jperdomo95** [damianof/large-scale-apps-my-vue3-project#6]
I have a strange issue, each time I try to run my tests with yarn test:unit the console outputs the following
SVGElement is not defined
And the test fails, even though I don't have SVGElement anywhere on my code.

**Comment by damianof** [comment]
Another reader emailed me about this as well and said that 
... installing ("webpack": "^4.0.0")

solved this problem. Unfortunately I won't have time to try this anytime soon. Let me know if that helps you.

**Comment by jperdomo95** [comment]
I tried the fix you commented but didn't work.
In the end, I re-installed the app but I selected **jest** as the test runner and it worked!
Thanks for the quick reply!
