### ISSUE TITLE
Unexpected mutation of "localeInfo" prop. eslintvue/no-mutating-props

### ISSUE THREAD

**Issue by KINGMJ** [damianof/large-scale-apps-my-vue3-project#7]
https://github.com/damianof/large-scale-apps-my-vue3-project/blob/8f1be7e4d19260fbf60bc11e70e1a070b310df11/composition-api/src/components/locale-selector/LocaleFlagRadio.component.vue#L9

**Comment by damianof** [comment]
Nice catch thank you. I'll try to get to this in the next few days.
