### ISSUE TITLE
How to use lerna or yarn workspace in your project?

### ISSUE THREAD

**Issue by minikiller** [damianof/large-scale-apps-my-vue3-project#8]
It is a great job for this project. I bought this book, and I develop a large scale apps based on your book. Now I have many module, I want to know how to solve this problem. I found lerna or yarn workspace can solve it. Do you know them? If you have plan to integrate it to your project. Thank.

**Comment by damianof** [comment]
I never worked with lernam and yarn it has been many years ago, sorry
